info:
    title: Forever
    author: 胡泽凡
    url: https://blog.aptzone.cc

##
defaults:
    # favicon: /images/favicon.ico
    # logo: 
    avatar: /images/favicon.ico

##主要颜色将影响按钮、进度条、链接和选定组件的颜色。
# colors:
#     primary:

##顶部进度条
# global:
#     scroll_progress:
#         bar: true
#         percentage: false

fontawesome: # select fontawesome versions you want to use, in order to reduce the loading time, select as few as possible
    thin: false # use fontawesome thin version or not
    light: false # use fontawesome light version or not
    duotone: false # use fontawesome duotone version or not
    sharp_solid: false # use fontawesome sharp-solid version or not


home_banner:
    style: fixed
    # image:
    #     light:
    #     dark:
    title: Love Forever
    subtitle:
        text: ["从来没有真正的绝境, 只有心灵的迷途", "大鹏一日同风起，扶摇直上九万里。", "Loading..."]
    # custom_font:
    #     enable: true
    #     family: false
    #     url: 
    social_links: 
        enable: true
        links:
            github: https://github.com/ZefanHu
            fa-solid fa-at: mailto:bufantech@outlook.com
        qrs:
            weixin: https://cdn.jsdelivr.net/gh/ZefanHu/blogImage@main/img/photo_2024-01-13_03-54-02.jpg


navbar:
  links:
    Home: # 一级菜单栏名称
      path: / # 网址，可以为相对路径或者绝对路径
      icon: fa-regular fa-house # Fontawesome图标名称（可选）
    Google: # 一级菜单栏名称
      path: https://www.google.com/ # 网址，可以为相对路径或者绝对路径
      icon: fa-brands fa-google # Fontawesome图标名称（可选）
    About: # 一级菜单栏名称
      icon: fa-regular fa-user # Fontawesome图标名称（可选）
      submenus: # 二级菜单栏
        Me: /about # 二级菜单栏名称：网址
        Github: https://github.com/EvanNotFound/hexo-theme-redefine

search: 
    enable: true
    preload: true

home: 
    sidebar: 
        enable: true
        position: left
        announcement:
        links:
            Archives: # Display name
                path: /archives # Path
                icon: fa-regular fa-archive # Icon, can be empty
            Tags: # Display name
                path: /tags # Path
                icon: fa-regular fa-tags # Icon, can be empty

articles:
    style:
        image_caption: true
        link_icon: true
    word_count:
        enable: true
        count: true
        min2read: false
    code_block: 
        copy: true
        font:
            enable:
            family:
            url:
    toc:
        enable: true
        max_depth: 3
        number: false
    copyright:
        enable: true
        default: all_rights_reserved
    lazyload: true
    recommendation:
        enable: true
comment:
    enable: true
    system: waline
    config:
        waline:
            serverUrl: https://blogcomment.aptzone.cc/

plugins:
  # RSS feed. Requires hexo-generator-feed (npm i hexo-generator-feed). See https://github.com/hexojs/hexo-generator-feed
  feed:
    enable: true # Whether to enable

footer:
    runtime: false
    icon: 
    customize: You're right

